services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=etudiant_db'
      - 'MYSQL_USER=etudiant_db'
      - 'MYSQL_PASSWORD=etudiant_db'
      - 'MYSQL_ROOT_PASSWORD=root_password'
    ports:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: